### PR TITLE
Issue #4: PlayerDB and Hypixel APIs should be called with unique CONFIG headers. 

### PR DESCRIPTION
**Pull request by devloves**
**List of changes:**

- created `generateApiConfig` function to dynamically generate API configurations.
- This function takes an `API name` and an optional `API key,` allowing flexibility in creating different configurations for `PlayerDB` and `Hypixel`.
- Separate Configurations for PlayerDB and Hypixel
- created regular expression for `UUID` Validation
- Incorporated console log statements in error-handling sections to provide more information about the errors.
- Added comments throughout the code to explain the purpose of it

### CODE REVIEW

**Review by StinkyDubeau — COMMENTED** [review]
I see that your IDE has changed the tab spacing from 4 to 2. This makes it difficult to review your code, as GitHub shows that nearly 100% of the original code has been modified.

I don't mind changing to 2-spaces, but I will have to review in detail later tonight to confirm functionality before merging.

If you can easily change the formatting back to 4-spaces, please do so. But only if it's easy for you to do.

Thank you for your contribution! I will be in touch. (:

**Comment by StinkyDubeau** [comment]
Hi Devansh,

I have been trying to run your branch for the past hour but I'm unfortunately running into errors. I trust your code is working, but I am struggling to debug because, like I mentioned above, *"your IDE has changed the tab spacing from 4 to 2. This makes it difficult to review your code, as GitHub shows that nearly 100% of the original code has been modified."*

While I am very grateful for your contribution (really, thank you so much!), I am going to close this pull request. I implore you to fix the line spacing and submit a new request. I will leave the issue open for now should you still wish to contribute.

```
TypeError: Cannot read properties of undefined (reading 'player')
    at translateJSON (file:///home/jake/Desktop/review/pixelstats/index.js:86:24)
    at file:///home/jake/Desktop/review/pixelstats/index.js:153:14
    at Layer.handle [as handle_request] (/home/jake/Desktop/review/pixelstats/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jake/Desktop/review/pixelstats/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/jake/Desktop/review/pixelstats/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/jake/Desktop/review/pixelstats/node_modules/express/lib/router/layer.js:95:5)
    at /home/jake/Desktop/review/pixelstats/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/jake/Desktop/review/pixelstats/node_modules/express/lib/router/index.js:346:12)
    at next (/home/jake/Desktop/review/pixelstats/node_modules/express/lib/router/index.js:280:10)
    at getStats (file:///home/jake/Desktop/review/pixelstats/index.js:141:3)

Node.js v20.10.0
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by devloves** [comment]
Yes i will fix the spacing issue and reopen a new pull request

**Comment by devloves** [comment]
I checked my VScode again and i am sure i used the space 4
image

can you maybe elaborate on the errors or issues you are getting ?

**Comment by StinkyDubeau** [comment]
Despite your VS code setting, something has definitely changed it to 2 spaces.

I see you have compile hero installed, it may be auto formatting the document.

Here's your screenshot with some scribbles added to show it's only 2-spaces. Excuse the crudeness, I'm on mobile.

image

**Comment by devloves** [comment]
Correct, it could possibly be because of compile hero

**Pull request closed without merging**
