### PR TITLE
Issue #4: API changes 

### PR DESCRIPTION
**Pull request by devloves**
**List of changes:**

- created `generateApiConfig` function to dynamically generate API configurations.
- This function takes an `API name` and an optional `API key,` allowing flexibility in creating different configurations for `PlayerDB` and `Hypixel`.
- Separate Configurations for PlayerDB and Hypixel
- created regular expression for `UUID` Validation
- Incorporated console log statements in error-handling sections to provide more information about the errors.
- Added comments throughout the code to explain the purpose of it

### CODE REVIEW

**Comment by devloves** [comment]
Fixed Spaces too. also before closing this one just ask for any changes, or bug fixes here

**Comment by devloves** [comment]
If you get any errors let me know

**Comment by devloves** [comment]
Oh while changing the spaces i accidently changed the spaces for the other files too, will open a new PR

**Comment by StinkyDubeau** [comment]
Ah, sorry I didn't realize that rejecting the other pull request closed the issue. That wasn't my intention.

**Comment by devloves** [comment]
i am also new to this XD

**Comment by devloves** [comment]
sorry if i messed up, first time working with open source

**Pull request closed without merging**
